[package]
name = "pacman"
version = "0.1.0"
edition = "2021"

[dependencies]
rusty_engine = "5.0.0"

[profile.dev]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 16